export const database = [
  // 'Ableton Live Auto Pan',
  // 'Ableton Live Beat Repeat',
  // 'Ableton Live Corpus',
  // 'Ableton Live Drum Bus',
  // 'Ableton Live EQ 3',
  // 'Ableton Live Erosion',
  // 'Ableton Live Frequency Shifter',
  // 'Ableton Live Grain Delay',
  // 'Ableton Live Hybrid Reverb',
  // 'Ableton Live Redux',
  // 'Ableton Live Spectral Resonator',
  // 'Ableton Live Spectral Time',
  // 'Ableton Live Vinyl Distortion',
  // 'Ableton Live Vocoder',
  'Accusonus Regroover',
  'Arturia Chorus JUN-6',
  'AudioThing Motor',
  'AudioThing Speaker',
  'AVOX 4 Articulator',
  'AVOX 4 Choir',
  'AVOX 4 Harmony Engine',
  'AVOX 4 Mutator',
  'Cableguys HalfTime',
  'CamelAudio CamelCrusher',
  'Dada Life Endless Smile',
  'Devious Machines Texture',
  'Eventide Blackhole',
  'Exponential Audio Excalibur',
  'FabFilter Saturn 2',
  'Goodhertz Lossy',
  'illformed Glitch 2',
  'iZotope NeoVerb',
  'iZotope Trash 2',
  'iZotope Vinyl',
  'iZotope VocalSynth 2',
  'Max for Live Granulator II',
  'MeldaProduction MUnison',
  'MeldaProduction SpectralPan',
  'Native Instruments Guitar Rig 5',
  'Oxford Inflator',
  'XLN Audio RC-20 Retro Color',
  'Soundtoys Crystallizer',
  'Soundtoys Decapitator',
  'Soundtoys Devil-Loc Deluxe',
  'Soundtoys EchoBoy',
  'Soundtoys FilterFreak',
  'Soundtoys Little AlterBoy',
  'Soundtoys Little Plate',
  'Soundtoys MicroShift',
  'Soundtoys PanMan',
  'Soundtoys PhaseMistress',
  'Soundtoys Radiator',
  'Soundtoys Tremolator',
  'Valhalla Shimmer',
  'Valhalla Space Modulator',
  'Valhalla Super Massive',
  'Waves Abbey Road Chambers',
  'Waves Abbey Road Vinyl',
  'Waves Berzerk Distortion',
  'Waves CLA Effects',
  'Waves J37 Tape',
  'Waves MDMX Distortion Modules',
  'Waves OVox Vocal ReSynthesis',
  'Waves Smack Attack',
  "Waves The King's Microphones",
  'Waves Torque',
  'Waves Vocal Bender',
  'Wavesfactory Cassette',
  'Wavesfactory SnareBuzz',
  'Xfer Records Dimension Expander',
  'Xfer Records Serum FX',
];
